apiVersion: v1
kind: Service
metadata:
  name: tasks
  namespace: default
  labels:
    app: tasks
spec:
  # ClusterIP — доступ только внутри кластера.
  # Для доступа снаружи используем kubectl port-forward.
  type: ClusterIP
  selector:
    # Балансирует трафик между всеми подами с меткой app=tasks.
    app: tasks
  ports:
    - name: http
      port: 8082        # порт сервиса (внутри кластера)
      targetPort: 8082  # порт контейнера
      protocol: TCP
