package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"
	"pz1/services/graphql/graph/generated"
	"pz1/services/graphql/graph/model"
	"pz1/shared/repository"

	"go.uber.org/zap"
)

// CreateTask is the resolver for the createTask field.
func (r *mutationResolver) CreateTask(ctx context.Context, input model.CreateTaskInput) (*model.Task, error) {
	desc := ""
	if input.Description != nil {
		desc = *input.Description
	}
	task, err := r.repo.Create(ctx, repository.Task{
		Title:       input.Title,
		Description: desc,
	})
	if err != nil {
		r.log.Error("graphql: create task failed",
			zap.String("component", "resolver"),
			zap.String("error", err.Error()),
		)
		return nil, fmt.Errorf("internal error")
	}
	r.log.Info("graphql: task created",
		zap.String("component", "resolver"),
		zap.String("task_id", task.ID),
	)
	t := repoTaskToModel(task)
	return &t, nil
}

// UpdateTask is the resolver for the updateTask field.
func (r *mutationResolver) UpdateTask(ctx context.Context, id string, input model.UpdateTaskInput) (*model.Task, error) {
	existing, err := r.repo.Get(ctx, id)
	if err != nil {
		if err.Error() == "task not found" {
			return nil, fmt.Errorf("task not found")
		}
		return nil, fmt.Errorf("internal error")
	}

	patch := existing
	if input.Title != nil {
		patch.Title = *input.Title
	}
	if input.Description != nil {
		patch.Description = *input.Description
	}
	if input.Done != nil {
		patch.Done = *input.Done
	}

	updated, err := r.repo.Update(ctx, id, patch)
	if err != nil {
		r.log.Error("graphql: update task failed",
			zap.String("component", "resolver"),
			zap.String("task_id", id),
			zap.String("error", err.Error()),
		)
		return nil, fmt.Errorf("internal error")
	}
	r.log.Info("graphql: task updated",
		zap.String("component", "resolver"),
		zap.String("task_id", id),
	)
	t := repoTaskToModel(updated)
	return &t, nil
}

// DeleteTask is the resolver for the deleteTask field.
func (r *mutationResolver) DeleteTask(ctx context.Context, id string) (bool, error) {
	err := r.repo.Delete(ctx, id)
	if err != nil {
		if err.Error() == "task not found" {
			return false, nil
		}
		r.log.Error("graphql: delete task failed",
			zap.String("component", "resolver"),
			zap.String("task_id", id),
			zap.String("error", err.Error()),
		)
		return false, fmt.Errorf("internal error")
	}
	r.log.Info("graphql: task deleted",
		zap.String("component", "resolver"),
		zap.String("task_id", id),
	)
	return true, nil
}

// Tasks is the resolver for the tasks field.
func (r *queryResolver) Tasks(ctx context.Context) ([]*model.Task, error) {
	tasks, err := r.repo.List(ctx)
	if err != nil {
		r.log.Error("graphql: list tasks failed",
			zap.String("component", "resolver"),
			zap.String("error", err.Error()),
		)
		return nil, fmt.Errorf("internal error")
	}
	return repoTasksToModel(tasks), nil
}

// Task is the resolver for the task field.
func (r *queryResolver) Task(ctx context.Context, id string) (*model.Task, error) {
	task, err := r.repo.Get(ctx, id)
	if err != nil {
		if err.Error() == "task not found" {
			return nil, nil
		}
		r.log.Error("graphql: get task failed",
			zap.String("component", "resolver"),
			zap.String("task_id", id),
			zap.String("error", err.Error()),
		)
		return nil, fmt.Errorf("internal error")
	}
	t := repoTaskToModel(task)
	return &t, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
